// front/src/components/Footer.vue
<template>
  <v-footer padless app absolute>
    <v-row
        justify="center"
        no-gutters
    >
      <v-btn
          color="grey"
          text
          rounded
          class="my-2"
          href="https://github.com/IESN-IG/IESN-Scheduler"
          target="_blank"
      >
        <v-icon>mdi-github</v-icon>
      </v-btn>
      <v-col
          class="py-4 text-center grey--text"
          cols="12"
      >
        Support : contact@thibaultclaude.be | Discord : <strong>tiiBz</strong>#1337
      </v-col>
    </v-row>
  </v-footer>
</template>

<script>
export default {
  name: "Footer"
}
</script>

<style scoped>
</style>

// front/components/Footer.jsx
import { Flex, IconButton, Text } from "@chakra-ui/react";
import { FaGithub } from "react-icons/fa";

const Footer = (props) => {
  return (
    <Flex
      direction="column"
      justifyContent="center"
      alignItems="center"
      width="100%"
      {...props}
    >
    <IconButton 
        variant="ghost"
        aria-label="Call Segun"
        size="lg"
        icon={<FaGithub />}
        isRound
        onClick={() => window.open("https://github.com/IESN-IG/IESN-Scheduler", "_blank") || window.location.replace("https://github.com/IESN-IG/IESN-Scheduler")}
    />
      <Text mb={5} opacity="0.5" textAlign="center">
        Support : me@thibaultclaude.be | Discord : <Text as="strong">tiiBz#1337</Text>
      </Text>
    </Flex>
  );
}

export default Footer;
